### PR TITLE
update 404 error page

### PR DESCRIPTION
**Pull request by gcolliso**

### CODE REVIEW

**Comment by gcolliso** [comment]
@derekcollison not sure what you were looking for wrt a new 404 error page but see if this one is ok for now
https://deploy-preview-910--nats-io.netlify.app/booboo

**Comment by derekcollison** [comment]
Maybe put 404 centered and above Whoops and remove the banner currently for the 404 designation.

**Comment by gcolliso** [comment]
updated based on comments - removed title banner and relocated 404 error msg.
https://deploy-preview-910--nats-io.netlify.app/booboo

**Comment by derekcollison** [comment]
Looks good, I would remove the Whoops.. But your call.

**Pull request merged**
