### PR TITLE
Ariane mapping microservice with nats

### PR DESCRIPTION
**Pull request by mffrench**
Hi NATS community,

here's my blog post about how we're migrating Ariane architecture from monolith to microservices oriented architecture with NATS.

Will be happy to read your comments and feedbacks.

Cheers,

Mathilde

### CODE REVIEW

**Comment by mffrench** [comment]
@bjflanne : thank you for these first feedbacks :) 

The Ariane Bus is the messaging infrastructure (NATS or RabbitMQ - this is the user choice even if we plan to setup NATS as default).

I added the NATS logo in the diagram, changed the title from "Ariane bus" to "Messaging bus" and the color to green meaning this is not part of Ariane code stack. 

The RabbitMQ plugin is the Ariane stack in charge of mapping RabbitMQ runtime to produce the diagram showed in the first tweet of this blog post. 

Let me know if you have other ideas to clarify this blog :)

**Comment by kozlovic** [comment]
LGTM

**Comment by ColinSullivan1** [comment]
LGTM

**Comment by chriscasper** [comment]
LGTM!

**Pull request merged**
