### PR TITLE
Add CONNECT protocol info

### PR DESCRIPTION
**Pull request by danielwertheim**
Not really sure what the valid values are and if it's a numeric value or a string. I got it presented as an integer over Slack. And basically `NULL` (or other than `1`) means not supported.

Feel free to correct/comment on this so that it becomes correct.

### CODE REVIEW

**Comment by kozlovic** [comment]
@danielwertheim `Protocol` is an int. `0` (or absent) means it is the original protocol that dates back to 2009. If value is `1`, it means that the client supports receiving `INFO` protocol asynchronously (in order to update the list of servers it can reconnect to). Older clients would "break" if they were to receive `INFO` outside of the connect handshake, hence the need to introduce this new field in the `CONNECT` protocol.

**Comment by danielwertheim** [comment]
Feels like `protocol_version` would have felt more expressive, but given your input, would this work then?

`protocol`: _optional int_. Sending `0` (or absent) indicates client supports original protocol. Sending `1` indicates that the client supports dynamic reconfiguration of cluster topology changes by asynchronously receiving `INFO` messages with known servers it can reconnect to.

**Comment by kozlovic** [comment]
@danielwertheim Yes, that would be perfect. Thanks!

**Comment by danielwertheim** [comment]
@kozlovic done

**Comment by kozlovic** [comment]
LGTM

**Pull request merged**
