### PR TITLE
New site setup

### PR DESCRIPTION
**Pull request by lucperkins**
@gcolliso This is ready for review.

### CODE REVIEW

**Comment by gcolliso** [comment]
Thanks Luc! Just in the process of reviewing. I appreciate all of your hard work!

**Comment by lucperkins** [comment]
No problem, @gcolliso! NATS is a vital project and it's very much my pleasure.

**Comment by lucperkins** [comment]
It’s been almost two months and this has not even garnered a cursory review, so I’m closing. I will be deeply reticent to lend my efforts to this project in the future.

**Comment by derekcollison** [comment]
Luc I think that is a totally statement. However I have been watching and love the work on the Vitess site and actually early this am asked for a meeting with you from our team to give feedback.

I apologize for the radio silence. Greatly appreciate your efforts.

**Comment by derekcollison** [comment]
We had a good meeting today regarding the site and the desire to have a similar flow as to Vitess and gRPC and others. We may need/want a bit different styling to more closely align with our established brand but this stuff looks good.

We have some action items on our side for content and will be working on that.

**Comment by lucperkins** [comment]
@derekcollison Thank you for your kind words. My message (long since deleted) was overly harsh and largely attributable to frustrations outside this project and this PR (it's a weird time!). Happy to continue to help. I may not be able to be 100% responsive to all concerns but I'll do the best that I can with my time and resources in the coming weeks.

**Comment by derekcollison** [comment]
Yes crazy times for sure! We have some action items on our side as we said from a content standpoint to adopt the flow you have been giving to other sites which we definitely want to adopt. So nothing on your plate for now, all on ours!

**Comment by gcolliso** [comment]
Hey @lucperkins, I am interested in having a users section like the one on Vitess's website. I was playing with it and can't seem to get the logos to expand to more than 3 columns. Might you have a suggestion?

**Comment by lucperkins** [comment]
@gcolliso I'd recommend adjusting the column sizes: https://bulma.io/documentation/columns/sizes. Right now they're set to `is-one-third` but you could change that to, say, `is-one-quarter`.

**Comment by gcolliso** [comment]
@lucperkins In doing more investigation of the new site design, I've noticed the download page clients are not divided into Community supported and Synadia supported. Could we get these delimited again? Also, could we schedule a meeting for you to go over some of your methods? Maybe I wouldn't have to bother you as much then :D

**Comment by lucperkins** [comment]
I undid that separation because it is, I believe, in violation of CNCF guidelines regarding

**Comment by lucperkins** [comment]
Undoing that separation was intentional. Highlighting clients maintained by a specific company as “official” clients does not comport with CNCF guidelines:

https://github.com/cncf/foundation/blob/master/website-guidelines.md

**Comment by gcolliso** [comment]
Is it acceptable then to designate preferred clients when multiples are listed like Redis?
https://redis.io/clients

**Comment by lucperkins** [comment]
@gcolliso This also does not comport with CNCF guidelines, particularly the principle that "the origin company should not be favored over any other companies offering the same services" (third paragraph).

Synadia, however, is welcome to provide a listing of the clients that it created/maintains on its web properties, potentially on the page linked to on the support page. You could, for example, create a "NATS support" page at synadia.com/nats and list the Synadia-supported clients there.

It should also be pointed out that some of the language on the support page (which I have not modified in this PR) also does not comport with our guidelines. But this can be addressed at a later date.

**Comment by lucperkins** [comment]
@gcolliso I had some discussions internally and I think it may be okay to have something like a "preferred" clients listing. Could you clarify what the selection criteria would be for that?

**Comment by gcolliso** [comment]
@lucperkins We consider those clients that are in the nats-io GitHub organization to be the preferred clients. These clients are generally maintained on a regular schedule by our named maintainers, either Synadia or Community. Some clients have been internal to the org for years, others have been donated by the community where the author is voted in as an official maintainer. These clients also tend to be the most popular with our user base and have more external contributions.

**Comment by lucperkins** [comment]
@gcolliso Ah, I see. Having official clients is totally fine if the criterion is that they're under the nats-io org. The issue was with calling them Synadia supported. I can update the templates.

**Comment by lucperkins** [comment]
@gcolliso Okay, sounds like we're 100% on the same page here 👍

**Comment by lucperkins** [comment]
@gcolliso I've updated the download pages to indicate official clients. You can see an example here: https://deploy-preview-538--nats-io.netlify.app/download/go/

**Comment by gcolliso** [comment]
@lucperkins cool thanks! I like the badge.

**Comment by gcolliso** [comment]
@lucperkins the documentation is great! - thanks much!

**Comment by lucperkins** [comment]
@gcolliso Glad it helps! Do feel free to let me know if other areas are unclear.

**Comment by gcolliso** [comment]
@lucperkins thanks for adding the privacy toggle back in - we also have a gdpr banner that shows across the top with a button to dismiss. I was playing with that but previously it was in the header.html and uses Javascript for the button but I can't seem to get it to display in the right place or have the button work.

**Comment by lucperkins** [comment]
@gcolliso Okay, I've added that

**Comment by gcolliso** [comment]
@lucperkins During our last conversation we had discussed putting the NATS Server and NATS Streaming Server details on the download page and not a separate client detail page. Is this something you were working on? Is it possible? TIA

**Comment by gcolliso** [comment]
Brilliant!

**Pull request closed without merging**
