### PR TITLE
Added Embedded Nats Java to addons file

### PR DESCRIPTION
**Pull request by madansp**

### CODE REVIEW

**Comment by gcolliso** [comment]
@scottf could you review this community contribution, please?

**Comment by scottf** [comment]
@gcolliso We already have 2 different "embedded" nats options for Java. One is our own, https://github.com/nats-io/java-nats-server-runner, one is already listed https://github.com/nats-io/nats-site/blob/main/data/addons.toml#L425

If you still want I can dig into it further but immediately I have two things. I would suggest the default branch for the project repo be changed from `master` to `main`. Also the license is MIT, I don't know if this is a problem with us or CNCF, but we do everything under Apache 2

**Comment by madansp** [comment]
@scottf As you suggested, I changed the default branch to `main`. I re-licensed the project to Apache-2.0.

**Comment by scottf** [comment]
@madansp Can you please let us know how this project is different than the 2 project's I have mentioned? The nats.io one is used for unit testing the Java client and although not perfect, it pretty extensive in how it can run the server including supporting custom on-the-fly config. The second one is heavily designed with Spring in mind. Is it possible that maybe you have some things that could be incorporated into the nats.io one? My personal preference would be to continue to improve that project instead of having another similar project, and we are happy to take contributions.

**Comment by bruth** [comment]
@madansp If you still want to pursue this contribution, feel free to respond to Scott's question and re-open.

**Pull request closed without merging**
