### PR TITLE
Update NATS Streaming Release info to v0.5.0

### PR DESCRIPTION
**Pull request by kozlovic**

### CODE REVIEW

**Comment by kozlovic** [comment]
@chriscasper if it looks good and once it is merged, how fast can we get a live update? I would like to announce the release, and in the past, people complained that the nats.io website was not reflecting the new release. Thanks!

**Comment by chriscasper** [comment]
I can deploy when ever you want me to. Just let me know.

**Comment by kozlovic** [comment]
Ok, I am going to merge, and when it is done, please deploy. Thanks!

**Comment by chriscasper** [comment]
@kozlovic latest is now live!

**Comment by kozlovic** [comment]
@chriscasper Thanks!

**Pull request merged**
