### PR TITLE
CLOMonitor: Add Linux Foundation Trademarks footer

### PR DESCRIPTION
**Pull request by arm4b**
I've seen an effort (https://github.com/nats-io/nats-server/pull/4923) by @philpennock to improve the CNCF CLOMonitor rating for NATS.

The rating shows here https://landscape.cncf.io/?selected=nats and is an indicator of the project following the best practices according to CNCF.

This should help passing the "Legal" CNCF CLOMonitor check: https://clomonitor.io/projects/cncf/nats#nats-server_legal by adding the LF trademarks footer to the website.

### CODE REVIEW

**Comment by gcolliso** [comment]
@arm4b Could this be placed on the right side of the footer under the CNCF logo?

**Comment by arm4b** [comment]
@gcolliso Sure, let's see how it looks like.

**Comment by arm4b** [comment]
1st
image
vs 2nd
image

**Comment by arm4b** [comment]
Also playing with versions.

3rd with bolder CNCF (to give more importance to "Incubating project"):
image

and 4th (bolder CNCF, lighter LF):
image

@gcolliso thoughts?

**Comment by gcolliso** [comment]
Thanks @arm4b - I prefer the 2nd option but would like the left and right sides of the footer to be top-aligned

**Comment by arm4b** [comment]
@gcolliso good catch! They should be aligned now

**Comment by gcolliso** [comment]
Better thanks. Last thing promise, I think the text should be two lines permanently and not just as flex. It infringes on the center too much on desktop.

**Comment by arm4b** [comment]
Check now, if I understood it right.

**Comment by gcolliso** [comment]
Great! Thank you!

**Comment by arm4b** [comment]
Thanks for review @gcolliso, good 📐 and 👀 !

**Comment by gcolliso** [comment]
LGTM

**Pull request merged**
