### PR TITLE
Update support to include Synadia links

### PR DESCRIPTION
**Pull request by bruth**

### CODE REVIEW

**Review by gcolliso — COMMENTED** [review]
@bruth Thanks for the updates. The term/name "Enterprise NATS" violates the CNCF/LF project naming convention though. We need to be more diligent with this on the NATS project site as that is hosted by CNCF. Even the current terminology with Synadia Enterprise NATS subscription is skirting the edge.

**Comment by bruth** [comment]
Ah, great point and understood. I can revert the name, are the links still OK to add?

**Comment by gcolliso** [comment]
Yes the links are a-ok! Thanks

**Comment by bruth** [comment]
Hopefully these changes are OK? Changed back to include "Subscription" and now the offerings are just listed under the Synadia header. In theory, other commercial offerings could be added in subsequent sections..

**Comment by gcolliso** [comment]
lgtm - thanks @bruth

**Pull request merged**
