### PR TITLE
Provide nats-site Dockerfile

### PR DESCRIPTION
**Pull request by mffrench**
Dear NATS community,

as I needed to install nats-site dependencies, I worked on a Dockerfile which could be useful for any NATS community bloggers. 

Let me know what you think.

Cheers,

Mathilde

### CODE REVIEW

**Comment by bjflanne** [comment]
Excellent, thanks @mffrench for sharing with us all so people can have a quick look...and looking fwd to your blog post as discussed ;)

**Comment by mffrench** [comment]
Currently writing the blog post and adding my first image : just saw I missed a proper gulp installation. Will correct this and come back to you when it's OK !

**Comment by mffrench** [comment]
I had to make a global npm install of gulp-cli to run gulp in the container. Documented on the README. 

Let me know if there is a better solution !

**Comment by bjflanne** [comment]
Thanks @mffrench -- @chriscasper may have some ideas on best approach here. Thanks for keeping us posted on this...

**Comment by chriscasper** [comment]
LGTM! Nicely done. Just tested it out. Will merge it in.

**Pull request merged**
