### PR TITLE
Add kotlin example

### PR DESCRIPTION
**Pull request by iivanf**
Hi, after talking to @scottf  I am going to make this PR for a blog about the example in koltin.
kind regards.

### CODE REVIEW

**Review by scottf — APPROVED** [review]
LGTM

**Comment by gcolliso** [comment]
@iivanf please review the updates and let me know if you are good with them.

**Comment by iivanf** [comment]
@gcolliso It's OK for me. Thanks to you all =)

**Comment by gcolliso** [comment]
@iivanf great! I will publish tomorrow and publicize on Twitter. What is your Twitter handle?

**Comment by iivanf** [comment]
@gcolliso it is @Iivanferro

**Pull request merged**
