### PR TITLE
Added php-nats-streaming client

### PR DESCRIPTION
**Pull request by byrnedo**
Added to releases.yaml

### CODE REVIEW

**Comment by byrnedo** [comment]
@bjflanne Any chance of getting this added?

**Comment by petemiron** [comment]
@byrnedo We'll get this added. I also updated the content section in downloads in #301

**Comment by byrnedo** [comment]
thanks @petemiron

**Comment by ColinSullivan1** [comment]
Closing this as we updated #301 to merge the 2 PRs for the php client.  Please refer to #301 moving forward for comments, etc.  Thanks!

**Pull request closed without merging**
