### PR TITLE
Restore PGP WKD functionality

### PR DESCRIPTION
**Pull request by philpennock**

### CODE REVIEW

**Comment by gcolliso** [comment]
lgtm - thanks @philpennock

**Comment by philpennock** [comment]
Test is:
```
curl -fSs $(gpg-wks-client --print-wkd-url pdp@nats.io | sed -e 's/openpgpkey\.nats\.io/deploy-preview-651--nats-io.netlify.app/' -e 's,/nats\.io/hu/,/hu/,') | gpg --import
```

That's made more complicated by `gpg-wks-client` emitting a URL of the form which assumes `openpgpkey.nats.io` as the website, so that there's also a different path to the file within the server.  This is not as easy as it should be to test.

**Comment by philpennock** [comment]
Once live and any CDN caches have expired their negative entries, these commands should work:

```
gpg --locate-external-key pdp@nats.io
gpg --locate-external-key derek@nats.io
```

It's the "not on the real site" which makes that more awkward for testing while still on the staging site.

**Comment by philpennock** [comment]
Okay, GnuPG has added client-side caching of WKD results; this appears to be undocumented.  This is probably the `dirmngr` component, but `gpgconf --kill all` was the hammer I used.  After that, the `gpg` invocations above worked.

**Pull request merged**
