### PR TITLE
Modify support statement to include all Apcera supported clients.

### PR DESCRIPTION
**Pull request by ColinSullivan1**
@bjflanne @chriscasper for review.

### CODE REVIEW

**Comment by mcqueary** [comment]
The new verbiage seems a little circular to me, in that it says we "support the clients we support". I think we need to link to an authoritative list of supported clients.

**Comment by ColinSullivan1** [comment]
@chriscasper How I can link to the "Apcera Supported Clients" download section here?

**Comment by chriscasper** [comment]
There are not any anchors built into the page so you can't deep link to just "Supported Clients" as of right now. So you'd just have to link to /downloads... Is that what you were thinking?

**Comment by ColinSullivan1** [comment]
Thank you Chris...  @chriscasper @bjflanne @mcqueary for review.

**Comment by chriscasper** [comment]
I would just change the url for the link to a relative one from https://nats.io/download to => /download, otherwise LGTM!

**Comment by ColinSullivan1** [comment]
@chriscasper Looks like you beat me to it...

**Pull request closed without merging**
